### ISSUE TITLE
Schema Validation - Problem

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#18]
I can easily get my DIGGS files that we generate to validate against the files in Github, but when I attempt to use the schema files located on the official DIGGS website, I don't get them validating at all.  Any suggestions?

[bad header.txt](https://github.com/DIGGSml/diggs-schema/files/4663375/bad.header.txt)
[good header.txt](https://github.com/DIGGSml/diggs-schema/files/4663376/good.header.txt)

**Comment by panars** [comment]
Dan @dponti was having this problem too. Here is what he had emailed me and Nick.

> Hi Peter - I figured out that the schema validation errors occur because of multiple import and include statements in the various schema files. These are there in order for each schema file to individually validate. and Oxygen ignores multiple imports, as is allowable in the standard.This works fine when pointing to files on a local directory on on the GitHub site, but not when pointing to the files on diggsml.org/schemas/2.5.a. I have no idea why this is the case. However, I found a workaround by pointing to Kernel.xsd instead of Complete.xsd - this appears to avoid the multiple import issue and file validation works fine. I'll post info to GitHub on this so that folks point to the correct location.
> 
> Still would be nice to know what is different about the diggsml.org site that causes this...

I wondered if it could be that there are multiple schemas available on diggsml.org/schemas ?
In other words, maybe Oxygen is pulling multiple schema files from the diggsml.org website?

**Comment by dponti** [comment]
Until we figure out the issues on the diggsml.org site, Diggs v 2.5.a instance documents should point to Kernel.xsd for validation instead of Complete.xsd as follows: 

xsi:schemaLocation="http://diggsml.org/schemas/2.5.a https://diggsml.org/schemas/2.5.a/Kernel.xsd"
