### ISSUE TITLE
Missing Value from DIGGScodes.xml

### ISSUE THREAD

**Issue by nickmachairas** [DIGGSml/diggs-schema#2]
_From @sdeaton75 on January 3, 2018 14:31_

The DIGGSCodes.xml may be missing a property for the LabPenetrometerTest result.  There is the abstract test procedure, but this particular one is missing the property for results. In the image below, I have added a proposed property.

![image](https://user-images.githubusercontent.com/2412948/34524226-b7de6d0a-f068-11e7-8e43-e5cac103e585.png)

_Copied from original issue: DIGGSml/DIGGSml.github.io#2_

**Comment by nickmachairas** [comment]
_From @sdeaton75 on January 3, 2018 14:54_

I also noticed there are various other abstract test procedures that are missing results.  LabResistivity is another example.

**Comment by dponti** [comment]
remolded_shear_strength_undrained, peak_shear_strength_drained, peak_shear_strength_undrained are currently results associated with LabPenetrometerTest. Are these correct? Any others?

Added resistivity property to LabResistivityTest.

**Comment by dponti** [comment]
Added compressive_strength_unconfined to the LabPenetrometerTest in file: DIGGSTestPropertyDefinitions.xml
