### ISSUE TITLE
Test tied to SampleProduced

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#21]
@dponti , @Rogerchandler 
As we have been working with DIGGS and OpenGround Cloud and HoleBASE we encountered something that we weren't sure how it is supported in DIGGS.  This revolves around the SamplingActivity/Sample Produced and the ensuing lab tests that can be performed on the sample produced.  

The question is - can a Test object (say an Atterberg Limit) be tied to a sampleProduced object?  Currently it seems it is only tied to the Project and SamplingFeature (location).  The Test has a depth in it so it is intrinsically related to the SampleProduced object by depth, but what happens if you have a SamplingActivity (SPT related) from 1-2.5' and then a second SamplingActivity (macrocore) from 1-6'.  Then you have 2 samples produced (1-2.5 and 1-6').  

There are two Atterberg test results at the same depth but the test results only have a depth in them of 1'. How do I know which one is tied to which SampleProduced? If the Test object had an href to the SampleProduced object then they could be associated correctly.

**Comment by Rogerchandler** [comment]
Scott, I think the sampleRef can be added to the specimen information in each test.  Would this work?

**Comment by sdeaton75** [comment]
I need more insight into what you mean @Rogerchandler  - when I look at the Test Object (which is where the Atterberg limit results are located), I don't see anything there to attach that to the "specimen". Do you have an example?

**Comment by dponti** [comment]
References to samples occur within the test procedure object attached to a test, not to the Test object itself, assuming that the procedure is a laboratory test procedure (thus applies to a sample specimen). All laboratory test procedures (eg. for Atterberg) have specimen properties - that contain Specimen objects - one of which is specific to soil specimens. The SoilSpecimen object contains a mandatory sampleRef property where you can point to the collected Sample object.
--
Daniel J Ponti, Ph.D.
Scientist Emeritus
Earthquake Science Center
U.S. Geological Survey
P.O. Box 158
Moffett Field, CA 94035
ph. (650) 439-2679



________________________________
