### ISSUE TITLE
Lithology structure for non USCS standardized states.

### ISSUE THREAD

**Issue by ross-cutts** [DIGGSml/diggs-schema#29]
The lithology structure is nice with the abundance codes. However, is there a concern that some of the DOT's data are not standardized on USCS? I know Maryland was using a custom lithology description until around 7 years ago.

**Comment by dponti** [comment]
DIGGS is not standardized on USCS. Any classification system or vocabulary of terms can be used, and it is incumbent on the data provider to define the terminology used, either by referencing a standard set of terms (such as USCS) or to point to a custom dictionary of terms whereby the terms used are defined.

The property <abundanceCode> is of type gml:CodeType. A codeType property is text that is intended to come from a controlled list of terms. Codetype elements contain an attribute named codeSpace, that is intended to identify the authority that defines the term or to point to a dictionary. So if one were defining the abundance of an lithological component as "common" as defined by the American Geosciences Institute, the xml snippet would look like:

<abundanceCode codeSpace="AGI">common</abundanceCode> The term "common" is defined by the authority identified in the codeSpace attribure. Alternatively, if, say CalTrans has it's own definition for what constitutes a common abundance, an identifier for CalTrans would be used:

<abundanceCode codespace="CalTrans">common</abundanceCode>.

This works ok where the authority designation is well known and their controlled terms are readily accessible. Ideally, the codeSpace attribute would point to an online dictionary, where the definition could be looked up programmatically, for example:

<abundanceCode codespace = "http://myAgencyDictionary.MyAgency.xml/#common">common</abundanceCode> Here the codespace is a pointer to an xml dictionary where the specific definition element has an id of "common".
