### ISSUE TITLE
Interbedded Rock Lithology

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#4]
We are curious as to how the componentlithology object is meant to be used.  We have a scenario where you have interbedded rock and people describe the larger component of rock as a record and then they have a 1:1 (or theoretically 1:M) child of the lithology that is the interbedded material that has a smaller percentage of the rock mass.  So for example, you might have data like this.  I am assuming the parent record would be the primaryLithology.  The interbedded record would be the ComponentLithology. Is that correct? Do you have an example that illustrates this?  

![image](https://user-images.githubusercontent.com/2412948/40678245-03bad7f6-634e-11e8-9026-2295c98c3fec.png)

**Comment by dponti** [comment]
HI Scott - 
Sorry for the delay. I was hoping to get to this last weekend and now I'm in the field and pretty slammed until early next week. However, the example you show is exactly what componentLithology is designed for. Each lithologic interval can have multiple componentLithology objects; the association attribute is used to describe how the component is distributed within the primary lithology (eg. interbedded, inclusions, etc.) and the abundance code (trace, few, common, etc) or abundancePercent is used to desribe how prominent the component is.  I will send an example by early next week.

**Comment by sdeaton75** [comment]
Dan do you have an example for this?

**Comment by dponti** [comment]
Catching up on loose threads - here is an example snippet of a lithologyObservation for a layer that overall is composed of 75% clay and 25% sand that is interbedded within the clay:

`            <lithologyObservation>
                <LithologyObservation gml:id="lo1">
                    <location>
                        <LinearExtent gml:id="lo1-le">
                            <gml:posList srsDimension="1" srsName="#lrs1">0 8.0</gml:posList>
                        </LinearExtent>
                    </location>
                    <trueTopObserved>true</trueTopObserved>
                    <trueBaseObserved>true</trueBaseObserved>
                    <primaryLithology>
                        <Lithology gml:id="lo1-li">
                            <classificationCode codeSpace="ASTM D2487 - 17e1">CL</classificationCode>
                            <lithDescription>Blue clay</lithDescription>
                         </Lithology>
                    </primaryLithology>
                    <componentLithology>
                        <ComponentLithology gml:id="lo1-c1" association="interbedded with the primary lithology">
                            <lithology>
                                <Lithology gml:id="lo1-li-c1">
                                    <classificationCode codeSpace="ASTM D2487 - 17e1" howDetermined="visual">SP</classificationCode>
                                    <lithDescription>Pale brown, poorly graded sand</lithDescription>
                                </Lithology>
                            </lithology>
                            <abundancePercent uom="%">25</abundancePercent>
                        </ComponentLithology>
                    </componentLithology>
                </LithologyObservation>
            </lithologyObservation>
`
The character of the component lithology is defined in the association attribute of the ComponentLithology object and comes from an enumerated list. Current enumerations in the list are:
1) uniformly distributed as a component of the primary lithology
2) interbedded with the primary lithology
3) incorporated as inclusions within the primary lithology

You would use component lithology(ies) to indicate a layer of interbedded lithology where the specific location(s) or depths of the interbeds are not important to record. If the locations of interbeds are important, then these beds should be encoded within their own separate layers (eg LithologyObservation) where you can define the location of each bed.
