### ISSUE TITLE
UU Triaxial Testing

### ISSUE THREAD

**Issue by VrMahmoudabadi** [DIGGSml/diggs-schema#46]
There are a couple of issues with the elements inside the Triaxial Testing object:

1- Under "TriaxialTestShearSatge" which is used for UU test, the "total pore water pressure at failure" element is required, however for UU test this parameter is not necessary and not recorded. The "total cell pressure" as confining pressure is what normally recorded. The test would not be valid against the schema if we leave this element empty or remove it from the object. 

2- Following the previous issue, under the "shearing increment" element, there is no place to input the cell pressure as confining pressure during the test, but instead there is "total pore water pressure" which is not necessary again.

3- There is no place defined under "Shearing Increment" for the sample deformation/deflection. Since there is an element for "axial load", we think that the deflection/deformation needs to be added to this element. By adding that, the users can record the sample behavior either in stress/strain or load/deformation format which are generally used in the practice.

4- the "waterContentPostShear" element under "TriaxialTestShearSatge" stage is a duplicate field. The value can be recorded under the "Soil Specimen" as a condition after the test completion.

**Comment by sdeaton75** [comment]
All of these changes have been implemented in 2.6
