### ISSUE TITLE
Lab Penetrometer TestProcedure Object missing

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#48]
When using Pydiggs to validate some of our DIGGS files for ODOT, we found that we were not handling pocket penetrometer performed in the lab correctly.  So, we started trying to build this out correctly and found that the "compressive_strength_unconfined" dictionary entry references the following object "procedure/diggs_geo:LabPenetrometerTest". 

![Capture](https://user-images.githubusercontent.com/2412948/227271140-9dfdd84d-7778-40a6-8b8c-bf1ddc17ff68.PNG)

When we look at the schema though for the 
https://diggsml.github.io/index.html#AbstractLaboratoryTestProcedure

It doesn't exist.  This object needs to be added or someone needs to let us know where it is :).

**Comment by sdeaton75** [comment]
This will be in 2.6 not fixing 2.5.

**Comment by dponti** [comment]
Added PocketPenetrometerTest to 2.6 as a laboratory test type to provide for specimen info.

**Comment by dponti** [comment]
Closed as completed
