### ISSUE TITLE
DIGGS Codes

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#5]
We have found another test result that needs to be incorporated into DIGGS.  The (Loss on Ignition Test) Organic Content is missing from the DIGGS Code list.  I have added them to my version of the document and highlighted them in red here and sent them to Dan via email, since I cannot attach the XML file to this issue. It doesn't require a schema change - just adding to the list.

![image](https://user-images.githubusercontent.com/2412948/40983044-b8ff9616-68ac-11e8-9e14-a3e92b80c53f.png)

**Comment by sdeaton75** [comment]
I realized I could add them as a zip file. So here they are.  [DIGGScodes 20180605.zip](https://github.com/DIGGSml/diggs-schema/files/2072814/DIGGScodes.20180605.zip)

**Comment by dponti** [comment]
Thanks, will incorporate.

**Comment by dponti** [comment]
Current definition file already has this, but the code is soil_organic_content
